# Secure Properties - Encrypted values
jira:
  password: "![YXGxMzdUy6t+vzxOvpMn2WznZQyevfG/g0ZH6ciYT4kym7TTHcGThfnDkR3856cho9/c2nJnipKDFbnXmElc7e0EmKbgI+ytcXahxkaKJ70Dh/79rOCsMTJAPw3qvRZ/WH0hTox0we9tgljnS//YBiMGh9EWD927OghPes8LmsgYY8GTKfIHYc9ZGB6uuNrRTFKRKAal07oBWu2uGsonjMvnu+qB6I5SEUHtzJog2At8dtIRQZd8b2ImCF5qaHrQ6YWB/oktVPIM7tdGTL1VAQ=="